project_id      = "adk-devops"
service_account = "github-integration-sa"
repo            = "google/adk-samples"
pool            = "github-pool"
oidc_provider   = "github-provider"
organization    = "google"
