identification:
  - Provide the Patient Id starting with MH.
  - Provide the gender and age of the patient.
  - Identify the admitting doctor of the patient.
situation:
  - Overall summary: This should contain Significant events from the patient's stay till the current shift eg. Day of stay post OP, ICU admissions etc. This information can be found in the Doctors Notes.
  - Patient Condition: This information can be found in Doctor Notes, Nursing Notes and Shift Assessment section.
  - Patient's Diet: This information can be found in Doctor and nurse notes section.
  - Drain: Indicate presence of Drain.
  - Foley's Catheter: Indicate presence of Foley catheter.
  - Event Notes: If there are any 'Event Notes' present, add the details as-is. If not present, indicate 'Not Present'
  - Medication Orders: Include the list of medications ordered along with dosage, exclude disposables like syringes, cotton swab or dressing etc. Group by ordered date.
  - Medication administered: identify the medications 'administered' to the patient along with the time of administration, if available. Do not confuse this with the medications prescribed.

background:
  - Provide details about the medical history of the patient. Include details about Comorbidities of the patient, if available.
  - Provide details about reasons for admission of the patient.
  - Provide details about prior medications of the patient, if available.
assessment:
  - Vitals: Details about Temperature, Pulse, SPO2, BP , Respiration, GCS etc. If any vitals are missing, mention it as ‘INCOMPLETE’.
  - EWS/MEWS: if missing, mention ‘INCOMPLETE’.
  - Intake/Output: Dietary intake and output if available
  - GRBS:
  - Pain score:
  - Fall Score:
  - Pressure score:
  - DVT Score:
  - Aspiration score:
recommendation:
  - To-Do activities: Include the list of to-do activities for the next shift nurse (based on the doctor's notes)
  - Medications to be administered: Include the list of medications to be administered to the patient based on the advise from the doctors.
  - Any other actions to be performed by the next shift nurse apart from the to-do activities eg. Hygiene routine, Bath & oral care (given or not).
patient_transfer:
  - Provide information about transfer of patient
